### ISSUE TITLE
AttributeError when adding integration - object has no attribute 'product_code'

### ISSUE THREAD

**Issue by natkins76** [bigbadblunt/homeassistant-lightwave2#111]
Hi,

Very new to this, so probably being really thick ... So apologies in advance!

I've just recently setup HA, and it's automatically picked up my Lightwave system using HomeKit .. but this doesn't seem to pull through any of the more fun features for the lights or power sockets like energy monitoring, etc., .. it also doesn't pull through my heating TRV's either (Honeywell HR92's) ... 

So just install HACS, and from there, installed this lightwave2 integration ... which I've read will do a lot more.

During the setup wizard it's asked for my lightwave credentials, which I've entered, but then immediately errors  ... giving the following error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lightwave2/__init__.py", line 84, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.10/site-packages/lightwave2/lightwave2.py", line 229, in async_get_hierarchy
    await self._async_read_groups()
  File "/usr/local/lib/python3.10/site-packages/lightwave2/lightwave2.py", line 268, in _async_read_groups
    self.get_featureset_by_featureid(y).product_code = x['productCode']
AttributeError: 'NoneType' object has no attribute 'product_code'

I've tried this with both the latest beta and the latest non-beta release and both do the same.

Like I said, probably me being very new to this and not really understanding it, but any help to get it up and running would be greatly appreciated.

**Comment by bigbadblunt** [comment]
Can you turn on full logging in the integration options and send me a full log please?

**Comment by natkins76** [comment]
Thanks for replying so quickly - I assume the attached is the full log you need - from what I can tell it seems to be successfully connecting to Lightwave and obtaining a lot of device data,  (I have a fair few lightwave devices - sorry!) ... but then erroring ... any help would be greatly appreciated.

[home-assistant_2023-03-15T22-26-07.219Z.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/10985032/home-assistant_2023-03-15T22-26-07.219Z.log)

**Comment by bigbadblunt** [comment]
I just pushed a new beta release. This should supress the problem and enable the integration to load, but I'm not entirely sure why it occurs. If you could send me another log that would be useful.

**Comment by natkins76** [comment]
Thanks, I've downloaded the latest beta from HACS, created the integration, added my user credentials ... although it gives a message saying successfully setup, the tile in integrations says 'Failed to set up' .... and there are no devices or entities .... The logs are now showing showing information after the 'NoneType' error .. latest log file attached.

[home-assistant_2023-03-18T12-44-03.232Z.log](https://github.com/bigbadblunt/homeassistant-lightwave2/files/11008571/home-assistant_2023-03-18T12-44-03.232Z.log)

**Comment by bigbadblunt** [comment]
OK - another attempt! I've just pushed another beta.

The problem seems to be that you have a device "Sonos - Study Sonos" that is some kind of "virtual product" that my integration doesn't know how to handle. I should now have set it up to ignore these. I've not come across the virtual products before. Seems like you can add Sonos products in to the app ? Out of curiousity, what does this do?

**Comment by natkins76** [comment]
Amazing ... that's now worked a treat ... it'll will give me many hours of fun setting all the devices up in dashboards .... So it was the Sonos bit causing an issue! .... Just recently Lightwave have introduced the ability to control 3rd party devices through their app ... I think at the moment it's just Sonos and Philips Hue ... I believe they only introduced this new functionality a few weeks ago.

Thanks again for your help ...

**Comment by bigbadblunt** [comment]
Curious. It looks like something your authentication somehow failed. What happens if you try again?

**Comment by natkins76** [comment]
I've tried multiple times, restarting HA and rebooting ... the logs seem to indicate ongoing data being retrieved from lightwave after encountering the error, but the integration continues to show as failed and none of the entities are active.  

I did try removing the L92 switch from my lightwave account and after a few reboots, the HA integration came back to lfellife ... I've just tried adding it again to my lightwave setup, restarted HA, and can't get the integration to load up ... just error ingredients again.

**Comment by bigbadblunt** [comment]
Hmmmm. I've pushed a new beta release that should stop the integration falling over I think. Let me know if it's any more reliable. 

However, something is not right. Halfway through reading the states of the devices, the Lightwave servers seem to stop sending back the expected messages, and instead send back an error.

Line 4325 of the log you provided `'success': False, 'error': {'source': 'server', 'group': 16, 'code': '200', 'message': 'stream-msgs: Channel is not authenticated.'}`

As I said, the new version should handle this more gracefully and not bring down the whole integration. But it's not going to necessarily function as expected. If you could monitor it and send some more logs if it doesn't behave, I can try and work out what's wrong.

**Comment by natkins76** [comment]
With a bit of trial and error, I think I may have pinpointed the problem ... The L92 switch has a boost function where you can set (in the Lightwave App), a target temperature and amount of time (the switch has a physical boost button and I guess the idea is to allow someone just to give the heating a short term boost manually, without having to go int he app, or change the normal schedules) .... When this is set in the app, the integration fails to load, when I remove the boost functionality in the app, the integration appears to load up and work ....

**Comment by bigbadblunt** [comment]
Strange. If you have the appetite to do a bit more debugging, then logs (on the latest beta) with and without the boost would be useful. If not, then no worries, let me know if you have problems in future.

**Comment by natkins76** [comment]
Thanks, will try to get the logs from both scenarios and send them over soon ... at the moment, for some reason it's taking quite a few reboots to get the integration to kick in each time so is taking a couple of hours to get it back online ... but will definitely get both over to you when I can.

**Comment by bigbadblunt** [comment]
I've just pushed another beta, someone spotted an error in my previous fix.
