### ISSUE TITLE
Can't get lightwave2 to show in integrations

### ISSUE THREAD

**Issue by ianphillpott** [bigbadblunt/homeassistant-lightwave2#13]
Im very new at Home Assistant. Currently running on a Pi2 just playing with it to see if it will do what I want whilst I await my Pi4 delivery.

I've managed to install HACS, gone into that on Home Assistant, installed the Lightwave2 intigration in HACS, checked it has actually put files in custom_components but despite restarts and clearing cache on browser for the life of me I can't get the Lightwave2 integration to appear to install it.

Am I being super dense? Do i need to have installed something else first to get it to work?

Help!!

**Comment by bigbadblunt** [comment]
Hi Ian,

Where are you getting stuck. Once it's installed you need to go to the integrations page and click on the + in the bottom right. Then it should appear in the list of new integrations - are you saying it doesn't show up here?

![image](https://user-images.githubusercontent.com/29158690/83546013-f4410280-a4f7-11ea-8e71-8ca7344cc449.png)

**Comment by ianphillpott** [comment]
Yes not showing up here so clearly i have borked something up but I can't for the life of me work out what?!

**Comment by bigbadblunt** [comment]
Can you send me your homeassistant.log file?

**Comment by ianphillpott** [comment]
yes I would love to. Where can I find this easily (told you I was new at this! Sorry!)

**Comment by ianphillpott** [comment]
Ignore me, just found it:

2020-06-02 20:21:00 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-02 20:21:24 ERROR (MainThread) [hass_nabucasa.iot] Error handling message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hass_nabucasa/iot.py", line 94, in _async_handle_handler_message
    result = await handler(self.cloud, message["payload"])
  File "/usr/local/lib/python3.7/site-packages/hass_nabucasa/iot.py", line 154, in async_handle_webhook
    return await cloud.client.async_webhook_message(payload)
  File "/usr/src/homeassistant/homeassistant/components/cloud/client.py", line 188, in async_webhook_message
    found["webhook_id"], request
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 79, in async_handle_webhook
    peer_ip = request[KEY_REAL_IP]
TypeError: 'MockRequest' object is not subscriptable
2020-06-02 20:21:29 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2020-06-02 20:21:38 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 295, in _handle_entity_registry_updated
    await self._sync_helper(to_update, to_remove)
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 239, in _sync_helper
    await self.async_get_access_token()
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 128, in async_get_access_token
    raise RequireRelink
homeassistant.components.cloud.const.RequireRelink
2020-06-02 20:21:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for lightwave2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-02 20:22:31 ERROR (MainThread) [homeassistant.components.upnp] Timeout fetching DGA2231 (1921SA827) data
2020-06-02 20:52:31 ERROR (MainThread) [homeassistant.components.upnp] Timeout fetching DGA2231 (1921SA827) data
2020-06-02 21:02:11 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.1.105
2020-06-02 21:02:11 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.1.105
2020-06-02 21:13:26 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2020-06-02 21:13:26 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 295, in _handle_entity_registry_updated
    await self._sync_helper(to_update, to_remove)
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 239, in _sync_helper
    await self.async_get_access_token()
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 128, in async_get_access_token
    raise RequireRelink
homeassistant.components.cloud.const.RequireRelink
2020-06-02 21:14:22 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2020-06-02 21:14:22 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 295, in _handle_entity_registry_updated
    await self._sync_helper(to_update, to_remove)
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 239, in _sync_helper
    await self.async_get_access_token()
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 128, in async_get_access_token
    raise RequireRelink
homeassistant.components.cloud.const.RequireRelink

**Comment by bigbadblunt** [comment]
Hmmm. I'm a bit stumped. The line 

```2020-06-02 20:21:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for lightwave2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.```

Shows the component is being loaded. And there aren't any subsequent errors. So I'm not sure why it's not in the integrations list. Let's try two things:

1) Is it in the list but in the wrong place? Try searching for "light" in the new integration 

![image](https://user-images.githubusercontent.com/29158690/83610145-fb5b2580-a576-11ea-9e63-bfd5d410940a.png)

2) Do you have all the files needed for the integration and the permissions are correct. You should have in the following files in custom_components/lightwave2

```
-rw-r--r-- 1 homeassistant homeassistant 4573 Jun  2 17:34 binary_sensor.py
-rw-r--r-- 1 homeassistant homeassistant 6597 Jun  2 17:34 climate.py
-rw-r--r-- 1 homeassistant homeassistant 2329 Jun  2 17:34 config_flow.py
-rw-r--r-- 1 homeassistant homeassistant  354 Jun  2 17:34 const.py
-rw-r--r-- 1 homeassistant homeassistant 5120 Jun  2 17:34 cover.py
-rw-r--r-- 1 homeassistant homeassistant 6546 Jun  2 17:34 __init__.py
-rw-r--r-- 1 homeassistant homeassistant 6724 Jun  2 17:34 light.py
-rw-r--r-- 1 homeassistant homeassistant  285 Jun  2 17:34 manifest.json
-rw-r--r-- 1 homeassistant homeassistant 4014 Jun  2 17:34 sensor.py
-rw-r--r-- 1 homeassistant homeassistant  595 Jun  2 17:34 services.yaml
-rw-r--r-- 1 homeassistant homeassistant 4965 Jun  2 17:34 switch.py
```
 and in custom_components/lightwave2/translations

```-rw-r--r-- 1 homeassistant homeassistant  687 Jun  2 17:34 en.json```

**Comment by ianphillpott** [comment]
Good news. Gone back to it this morning and it has decided to appear! Not a scooby f-ing doo why the hell it wasnt there before! But so far all installing fine. 

Thanks for getting back at me, even if we did nothing different and it just decided to work!

(Next bit of fun will be seeing how well it moves across to the Pi4!)

**Comment by bigbadblunt** [comment]
OK - most likely it was still installing the dependencies in the background. For info, if a component needs additional libraries to work, HA will automagically go off in the background and install them. This is possibly what happened here, with the component not starting until the required dependencies had been installed. Particularly if it was a new install of HA, there might have been other things queued up to install before the lightwave library.

I don't get your comment on the heating - anything that I need to look at?

**Comment by ianphillpott** [comment]
TRV's can either be set by temperature (i.e. if below temp x then open TRV - I have always found this bloody irritating as you can guarantee the temp will just tip either above or below a set temp during a movie and then they start wurring like demented things) or they can also be set in position 0 1 2 3 4 and 5. I use this method as i can then control when the valve is opening / closing. I can't find an option to do this. It may be there and i'm just looking in the wrong place!

**Comment by ianphillpott** [comment]
Also I am missing one device - The toilet radiator. Showing in the lightwave app but not on Hass. All others seem to be in. Is it worth removing it from the app and adding again to see if picked up?

**Comment by bigbadblunt** [comment]
I think you're the first person to try a TRV. I haven't coded the component to be able to support TRVs, so it'll just be using the code from something similar (I'm surprised it works, and this is probably also the reason that your other radiator isn't getting picked up). I'm very happy to try and add this, if you have some time to send me log files and a bit of patience to try some new releases and give me feedback.

Can you increase the level of logging please and send me an new log? You'll need to add the following lines to your `configuration.yaml` file and then restart HA.

```
logger:
  default: warning
  logs:
    lightwave2.lightwave2: debug
```

I have opened a new issue (#14) for this. I will close this issue and let's pick it up in the other thread.

**Comment by bigbadblunt** [comment]
PS also, if you could use the app to change the settings on the TRV, then that should be picked up by the logging and give me something to work with. Cheers.
