### ISSUE TITLE
Since this mornings update and restart

### ISSUE THREAD

**Issue by Humphaz** [bigbadblunt/homeassistant-lightwave2#16]
Logger: homeassistant.config_entries
Source: custom_components/lightwave2/__init__.py:102
First occurred: 1:30:25 PM (1 occurrences)
Last logged: 1:30:25 PM

Error setting up entry Lightwave 2 for lightwave2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/lightwave2/__init__.py", line 102, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.7/site-packages/lightwave2/lightwave2.py", line 210, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.7/site-packages/lightwave2/lightwave2.py", line 247, in async_update_featureset_states
    x.features[y][1] = value["items"][0]["payload"]["value"]
KeyError: 'payload'

**Comment by bigbadblunt** [comment]
HI, I can't reproduce (it's working ok for me). Can you turn on debugging and send me the log file please?

Add the following to `configuration.yaml`
```
logger:
  default: warning
  logs:
    lightwave2.lightwave2: debug
    custom_components.lightwave2: debug
```

**Comment by Humphaz** [comment]
It fixed itself this morning during its planned restart?

Weird. I will activate logger next time, forgot, my apologies, evidently you've created self healing code.

:o)

**Comment by bigbadblunt** [comment]
No worries. Most likely a glitch in the response from the lightwave servers.
