### ISSUE TITLE
Broken!!

### ISSUE THREAD

**Issue by ianphillpott** [bigbadblunt/homeassistant-lightwave2#28]
Just updated to core 2021-1.5 and it's all stopped working!!

This is in the log...... 

2021-01-24 17:06:39 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration lightwave2 - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 64, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 158, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 76, in async_get_integration_with_requirements
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 123, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 54, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3125, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 789, in contains
    item = parse(item)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by ianphillpott** [comment]
Not sure if you need all this but:

## System Health

version | 2021.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.79-v7l
arch | armv7l
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4998
Installed Version | 1.10.1
Stage | running
Available Repositories | 710
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 4, 2021, 12:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | 2021.01.7
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 7.1 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.0), File editor (5.2.0), AppDaemon 4 (0.3.2), Duck DNS (1.12.4), Bitwarden RS (0.6.2), RPC Shutdown (2.2), Terminal & SSH (8.10.0), Git pull (7.12), Ring Livestream (1.35)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
mode | auto-gen
resources | 0

</details>

**Comment by bigbadblunt** [comment]
Ian, I can't reproduce this. I just upgraded to 2021-1.5 with no problem.

What version of the integration are you running?

Have you restarted to see if it was something intermittent?

**Comment by ianphillpott** [comment]
3.0.1beta

Left both HA and Lightwave hubs completely unplugged last night. Rebooted both. Still no luck.

If I remove and reinstall the add-on will I lose all my integrations etc or when it reloads will all the devices come back as they are now with same IDs etc?

**Comment by bigbadblunt** [comment]
They should come back as they are now.

**Comment by bigbadblunt** [comment]
Before you reinstall, can you post the contents of 

CONFIG_DIRECTORY/custom_components/lightwave2/manifest.json

**Comment by bigbadblunt** [comment]
Sorry, one more question. Did you just upgrade the HA version, or did you change anything else at the time it broke? In particular did you change the version of the integration?

**Comment by bigbadblunt** [comment]
Before you reinstall, something else to try. I have just pushed a new version v3.2.0beta (which fixes some other issues). Can you try upgrading to this, which might fix any problems with your files.

**Comment by ianphillpott** [comment]
Don't *think* I changed anything! 

Will download that file then play fingers crossed when deleting and reinstalling!

**Comment by ianphillpott** [comment]
{
  "domain": "lightwave2",
  "name": "Lightwave v2 (Smart Series) custom component",
  "documentation": "https://github.com/bigbadblunt/homeassistant-lightwave2",
  "dependencies": [],
  "codeowners": ["@bigbadblunt"],
  "requirements": ["lightwave2==0.6.20"],
  "config_flow": true
}

**Comment by bigbadblunt** [comment]
manifest.json looks fine

**Comment by ianphillpott** [comment]
So removed and reinstalled (now 3.2beta) and rebooted after removal and after reinstall.

No luck. 😭

**Comment by ianphillpott** [comment]
This is in the Core log....

  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 419, in execute
    n.execute_aggregate(self, set_)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 521, in execute_aggregate
    self.execute(uow)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2021-01-27 09:44:53.239889', '2021-01-27 09:44:53.239889', '6e1704fa629a0e108a7780acdc81a64d', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
2021-01-27 09:45:07 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2021-01-27 09:44:59.266367', '2021-01-27 09:44:59.266367', '7b58720529facdf35d4feaaecb5b1f75', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
2021-01-27 09:45:07 ERROR (Recorder) [homeassistant.components.recorder] Error saving events: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2021-01-27 09:44:59.266367', '2021-01-27 09:44:59.266367', '7b58720529facdf35d4feaaecb5b1f75', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 454, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 509, in _commit_event_session
    self.event_session.flush()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 419, in execute
    n.execute_aggregate(self, set_)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 521, in execute_aggregate
    self.execute(uow)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2021-01-27 09:44:59.266367', '2021-01-27 09:44:59.266367', '7b58720529facdf35d4feaaecb5b1f75', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6)

None of this seems good to me 🤨

**Comment by bigbadblunt** [comment]
This one's not my fault :)

```
2021-01-27 09:45:07 ERROR (Recorder) [homeassistant.components.recorder]
database disk image is malformed
```

Deleting home-assistant_v2.db should fix this error. You'll lose all your history but nothing else bad should happen.

It's strange that you're getting an error in the lightwave component and others aren't, and also that you now have errors in your log file.

Possible problems:

- failed upgrade; solution is to wait for the next release of HA and then see if upgrading to that fixes it
- failing SD card; solution is to get an new SD card and reinstall everything :(

You should take a backup of your .homeassistant folder asap.

**Comment by ianphillpott** [comment]
Hmm. So have deleted the db but didn't seem to do much.
Re-removed the integration, removed the repository, and disabled a few other things in config to make sure it wasn't something eles.
Rebooted
Re installed the repository
Rebooted
Attempted to install the integration, it flashes momenterily that it is installing, please wait, then goes back to the integration screen and doesn't appear to have installed.
If you try again it then just says installing please wait and has the spinning circle and doesnt clear.....

Something is not right with my HA! Praying they bring out an update very soon!!!

**Comment by ianphillpott** [comment]
Good news, the recent core update to 2021.2.0 sorted the issue.
Reinstalled the Lightwave component and all good.

Bad news is that it changed the device id's borking up a few scripts but easily fixable. 

So repairing then taking a back up before 2021.2.1 (and before EVERY upgrade going forward!)

Cheers!!

**Comment by bigbadblunt** [comment]
Thanks for confirming.
