### ISSUE TITLE
Power/Energy sensors/statistics stopped working after v3.5.1

### ISSUE THREAD

**Issue by araines** [bigbadblunt/homeassistant-lightwave2#48]
I'm using the following products:
* L24 (4-gang light switch)
* L22 (2-gang light switch)
* L21 (1-gang light switch)
* LW600 (clamp energy sensor)

With version v3.5.1 I get a "total consumption" and "current consumption" entity for each device, i.e. 4 total and 4 current for the 4-gang L24 switch.

With version v3.5.3 or v3.5.6 installed those entities become unavailable .

I found the following error in my logs (v3.5.6):
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 128, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 532, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 537, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/lightwave2/sensor.py", line 13, in <module>
    SensorEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'entity_category'
```

**Comment by bigbadblunt** [comment]
Are you on the latest version of HA (2021.11)? The "entity_category" thing is new in the latest version.

(Apologies, I really should have mentioned this in the release notes).

**Comment by araines** [comment]
Ah apologies - I hadn't upgraded yet, let me check that out.

**Comment by araines** [comment]
Yup, that fixed it.  Thanks for pointing me in the right direction!

**Comment by bigbadblunt** [comment]
No worries, I definitely need to try and remember to signpost these things better.
