### ISSUE TITLE
sensor.linkplus_dawn_time provide state 'T080724', while it has device class 'timestamp'

### ISSUE THREAD

**Issue by uvjim** [bigbadblunt/homeassistant-lightwave2#53]
After an upgrade to HASS 2021.12 I'm seeing a lot of occurrences of the following in the logs.

```
Logger: homeassistant
Source: components/sensor/__init__.py:390
First occurred: 11 December 2021, 21:53:39 (1210 occurrences)
Last logged: 20:54:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = ciso8601.parse_datetime(str(value))
ValueError: Invalid character while parsing year ('T', Index: 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 390, in state
    raise ValueError(
ValueError: Invalid date/datetime: sensor.linkplus_dawn_time provide state 'T080724', while it has device class 'timestamp'
```

**Comment by bigbadblunt** [comment]
Should be an easy fix. I think it will still work until 2022.2, but will try and fix soon to tidy up the log.

**Comment by bigbadblunt** [comment]
Hopefully fixed

https://github.com/bigbadblunt/homeassistant-lightwave2/releases/tag/v3.5.9

**Comment by uvjim** [comment]
Just upgraded and restarted HASS.
All looking good now. Thanks.
