### ISSUE TITLE
Errors in log after uprading to HASS 2022.4

### ISSUE THREAD

**Issue by uvjim** [bigbadblunt/homeassistant-lightwave2#64]
Hi,

Since upgrading to HASS 2022.4 the following errors now appear in the logs.

![image](https://user-images.githubusercontent.com/8431065/162498582-22b1a7dd-caf3-405b-8dd3-d99a85807be5.png)

A closer look at the error for the light integration shows this may be down to the following: https://github.com/home-assistant/core/pull/69015

```
Logger: homeassistant.components.light
Source: helpers/entity_registry.py:529
Integration: Light (documentation, issues)
First occurred: 19:09:41 (2 occurrences)
Last logged: 19:09:41

Error adding entities for domain light with platform lightwave2
Error while setting up lightwave2 platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Comment by bigbadblunt** [comment]
This might be painful as I currently don't have a lightwave install at home, so I can't test my code. I've pushed a new version that I think fixes this, but can't test it myself. Let me know if it works.

**Comment by uvjim** [comment]
That seems to have done it. Thanks.
