### ISSUE TITLE
LW929 - Home & Away Remote support missing

### ISSUE THREAD

**Issue by xela1** [bigbadblunt/homeassistant-lightwave2#75]
I received a home and away remote for free years ago but never used it, thought I'd have a play but the device doesn't seem to be supported fully.

It is detected, but the only entity is Signal Strength, it also doesnt seem to trigger a lightwave2.click event

Below is the feature details for it:

```
{
            "deviceId": "5df8b6728522075debd21ad8-39-3157346060+1",
            "name": "Home Away",
            "productCode": "LW929",
            "featureSets": [
                {
                    "featureSetId": "5df8b6728522075debd21ad8-62722fd6ca96eb0b7d75c6b2",
                    "name": "Home Away 1",
                    "features": [
                        {
                            "featureId": "5df8b6728522075debd21ad8-755-3157346060+1",
                            "type": "buttonPress",
                            "writable": false
                        },
                        {
                            "featureId": "5df8b6728522075debd21ad8-757-3157346060+1",
                            "type": "rssi",
                            "writable": false
                        },
                        {
                            "featureId": "5df8b6728522075debd21ad8-758-3157346060+1",
                            "type": "identify",
                            "writable": true
                        }
                    ]
                },
                {
                    "featureSetId": "5df8b6728522075debd21ad8-62722fd6ca96eb0b7d75c6b3",
                    "name": "Home Away 2",
                    "features": [
                        {
                            "featureId": "5df8b6728522075debd21ad8-756-3157346060+1",
                            "type": "buttonPress",
                            "writable": false
                        }
                    ]
                }
            ],
            "product": "LW929",
            "device": "N/A",
            "desc": "Home & Away Remote",
            "type": "lwrfTwoWay_v1",
            "cat": "Sensors",
            "gen": 1
        }
```

Event for Away button press

```
2022-05-04 09:12:58 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=22=252*eu=west=1*compute*internal=92325","transactionId":4097059,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1651651977941,"featureId":"5df8b6728522075debd21ad8-756-3157346060+1","deviceId":39,"type":"buttonPress","channel":1,"writable":false,"stateless":false,"virtual":false,"value":1,"status":"ok"},"success":true,"itemId":18}]}', extra='')
2022-05-04 09:12:58 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=22=252*eu=west=1*compute*internal=92325","transactionId":4097061,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1651651977954,"featureId":"5df8b6728522075debd21ad8-756-3157346060+1","deviceId":39,"type":"buttonPress","channel":1,"writable":false,"stateless":false,"virtual":false,"value":0,"status":"ok"},"success":true,"itemId":20}]}', extra='')
```

Event for Home button press

```
2022-05-04 09:12:50 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=22=252*eu=west=1*compute*internal=92325","transactionId":4096693,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1651651970716,"featureId":"5df8b6728522075debd21ad8-755-3157346060+1","deviceId":39,"type":"buttonPress","channel":0,"writable":false,"stateless":false,"virtual":false,"value":1,"status":"ok"},"success":true,"itemId":15}]}', extra='')
2022-05-04 09:12:50 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=22=252*eu=west=1*compute*internal=92325","transactionId":4096695,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1651651970729,"featureId":"5df8b6728522075debd21ad8-755-3157346060+1","deviceId":39,"type":"buttonPress","channel":0,"writable":false,"stateless":false,"virtual":false,"value":0,"status":"ok"},"success":true,"itemId":17}]}', extra='')
```

**Comment by bigbadblunt** [comment]
Thanks, should be easy to add. I normally try and make devices appear similar in ha to how they appear in the lw app. How does this show up there?

I'll add in the click events, but not sure if I should also be exposing some kind of sensor?

**Comment by xela1** [comment]
> How does this show up there?

It shows up as two tiles in the room it's in [Device Name] 1 and [Device Name] 2. if you click the button it momentarily changes to the 'on' state and then goes off again.

I don't believe there is a sensor of any kind, they just seem to have classified it under sensors

**Comment by bigbadblunt** [comment]
Do you also get a `consumer_handler: Event received (%s %s %s), calling callbacks` message in the log?

I've added some extra code that might detect these presses.

**Comment by xela1** [comment]
Will test when I can, at the moment its struggling to create the websocket:

`2022-05-15 12:24:02 INFO (MainThread) [lightwave2.lightwave2] async_sendmessage: Websocket closed, reconnecting
2022-05-15 12:24:02 DEBUG (MainThread) [lightwave2.lightwave2] connect_to_server: Connecting to websocket
2022-05-15 12:24:02 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: [contents hidden for security]
2022-05-15 12:24:02 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Message sent, waiting for acknowledgement from server
2022-05-15 12:24:07 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Timeout waiting for response to : 9
2022-05-15 12:24:07 INFO (MainThread) [lightwave2.lightwave2] async_sendmessage: Send failed, resending message (attempt 2)
2022-05-15 12:24:07 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: [contents hidden for security]
2022-05-15 12:24:07 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Message sent, waiting for acknowledgement from server
2022-05-15 12:24:12 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Timeout waiting for response to : 9
2022-05-15 12:24:12 INFO (MainThread) [lightwave2.lightwave2] async_sendmessage: Send failed, resending message (attempt 3)
2022-05-15 12:24:12 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: [contents hidden for security]
2022-05-15 12:24:12 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Message sent, waiting for acknowledgement from server
2022-05-15 12:24:17 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Timeout waiting for response to : 9
2022-05-15 12:24:17 INFO (MainThread) [lightwave2.lightwave2] async_sendmessage: Send failed, resending message (attempt 4)
2022-05-15 12:24:17 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: [contents hidden for security]
2022-05-15 12:24:17 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Message sent, waiting for acknowledgement from server
2022-05-15 12:24:22 DEBUG (MainThread) [lightwave2.lightwave2] async_sendmessage: Timeout waiting for response to : 9
2022-05-15 12:24:22 INFO (MainThread) [lightwave2.lightwave2] async_sendmessage: Send failed, resending message (attempt 5)
2022-05-15 12:24:22 INFO (MainThread) [lightwave2.lightwave2] async_sendmessage: Websocket closed, reconnecting
`

**Comment by bigbadblunt** [comment]
I had issues earlier where I wasn't getting any messages back from the server, looks like a similar problem. Let me know if it doesn't resolve itself.

**Comment by xela1** [comment]
Still having issues, is there a way to extend the timeout, just wondering if my HA is taking a little too long to connect for some reason?

**Comment by xela1** [comment]
Pressing either the home or away buttons seems to crash the integration:

```
2022-05-20 14:34:16 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Received WSMessage(type=<WSMsgType.TEXT: 1>, data='{"version":1,"senderId":"1.ip=10=192=21=43*eu=west=1*compute*internal=90103","transactionId":16110670,"direction":"notification","class":"feature","operation":"event","items":[{"payload":{"time":1653053656678,"featureId":"5df8b6728522075debd21ad8-756-3157346060+1","deviceId":39,"type":"buttonPress","channel":1,"writable":false,"stateless":false,"virtual":false,"value":1,"status":"ok"},"success":true,"itemId":14}]}', extra='')
2022-05-20 14:34:16 DEBUG (MainThread) [lightwave2.lightwave2] consumer_handler: Event received (5df8b6728522075debd21ad8-756-3157346060+1 <lightwave2.lightwave2.LWRFFeature object at 0xaee769e8> 1), calling callbacks ['async_central_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback', 'async_update_callback']
2022-05-20 14:34:16 DEBUG (MainThread) [custom_components.lightwave2] Central callback
2022-05-20 14:34:16 DEBUG (MainThread) [custom_components.lightwave2.sensor] Button (light) press event: sensor.home_away_signal_strength_2 1
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 188, in _consumer_handler
  File "/config/custom_components/lightwave2/sensor.py", line 140, in async_update_callback
    self._hass.bus.fire("lightwave2.click",{"entity_id": self.entity_id, "code": kwargs["new_value"]},

```

**Comment by bigbadblunt** [comment]
Are there no more log lines after that? Looks like you're missing the end of a line?

**Comment by xela1** [comment]
I think my grep probably cut it off, the log has rotated now, will get it to fail again and send through

**Comment by xela1** [comment]
```
2022-05-20 18:13:39 DEBUG (MainThread) [custom_components.lightwave2] Central callback
2022-05-20 18:13:39 DEBUG (MainThread) [custom_components.lightwave2.sensor] Button (light) press event: sensor.home_away_signal_strength_2 1
2022-05-20 18:13:39 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 188, in _consumer_handler
    func(feature=feature.name, feature_id=feature.id, prev_value = prev_value, new_value = value)
  File "/config/custom_components/lightwave2/sensor.py", line 140, in async_update_callback
    self._hass.bus.fire("lightwave2.click",{"entity_id": self.entity_id, "code": kwargs["new_value"]},
AttributeError: 'LWRF2Sensor' object has no attribute '_hass'

```

**Comment by bigbadblunt** [comment]
I've pushed a new release.

**Comment by xela1** [comment]
Working perfectly, thanks!
