### ISSUE TITLE
Error regarding climate

### ISSUE THREAD

**Issue by BNWEIN** [bigbadblunt/homeassistant-lightwave2#8]
Hi

I’m not using Lightwave for heating in any way, but since the latest update I’m getting this error on startup 

It doesn’t seen to be affecting anything but I’d like to stop it if possible? 

Log Details (ERROR)
Fri Oct 18 2019 22:44:39 GMT+0100 (BST)

Unable to prepare setup for platform climate.lightwave2: Platform not found

**Comment by BNWEIN** [comment]
Fri Oct 18 2019 22:44:39 GMT+0100 (BST)

Error loading custom_components.lightwave2.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 117, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/lightwave2/climate.py", line 4, in <module>
    from homeassistant.components.climate.const import (
ModuleNotFoundError: No module named 'homeassistant.components.climate.const'

**Comment by BNWEIN** [comment]
I’m using home assistant 0.87 by the way.

**Comment by bigbadblunt** [comment]
Hi, the internal structure of HA has changed so much since 0.87 that it's not possible for me to make the climate component backwards compatible.

If it bothers you to have the error in the log (I understand that feeling :) ) then you could edit `custom_components/lightwave2/__init.py__` and remove lines 74 and 75 where the climate platform is set up ( remove the code
`hass.async_create_task(
        async_load_platform(hass, 'climate', DOMAIN, None, config))`
)
