### ISSUE TITLE
Not loading after update to 2022.6.7

### ISSUE THREAD

**Issue by incarvr6** [bigbadblunt/homeassistant-lightwave2#86]
Not loading after update
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/lightwave2/__init__.py:83
Integration: Lightwave v2 (Smart Series) custom component (documentation)
First occurred: 17:32:35 (1 occurrences)
Last logged: 17:32:35

Error setting up entry Lightwave for lightwave2
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 135, in _async_sendmessage
    await asyncio.wait_for(waitflag.wait(), timeout=5.0)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lightwave2/__init__.py", line 83, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 223, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 265, in async_update_featureset_states
    value = await self.async_read_feature(y.id)
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 284, in async_read_feature
    return await self._async_sendmessage(readmess)
  File "/usr/local/lib/python3.9/site-packages/lightwave2/lightwave2.py", line 139, in _async_sendmessage
    self._transactions.pop(message._message["transactionId"])
KeyError: 45
`

**Comment by bigbadblunt** [comment]
I can't reproduce this. It looks like a (temporary) connectivity error. Can you try restarting and confirm the error persists?

**Comment by bigbadblunt** [comment]
Closing due to inactivity.
