### ISSUE TITLE
Integration fails to set up

### ISSUE THREAD

**Issue by mSobhy90** [bigbadblunt/homeassistant-lightwave2#89]
I've just added the integration and entered my email and password and this is what shows in the integration tab.
<img width="262" alt="Screenshot 2022-07-15 at 11 30 13" src="https://user-images.githubusercontent.com/1512973/179206463-eba50803-21e4-4c87-a5a1-ed453546310e.png">

HACS LW Plugin Version: `v3.5.15`
HACS Version: `1.26.2`
Home Assistant Version: `2022.7.5`

Any idea what might be causing this? I don't have public API enabled.

Thanks

Log 👇 
```
Logger: homeassistant.config_entries
Source: custom_components/lightwave2/__init__.py:83 
Integration: Lightwave v2 (Smart Series) custom component ([documentation](https://github.com/bigbadblunt/homeassistant-lightwave2)) 
First occurred: 11:33:51 (1 occurrences) 
Last logged: 11:33:51

Error setting up entry <EMAIL_HERE> for lightwave2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lightwave2/__init__.py", line 83, in async_setup_entry
    await link.async_get_hierarchy()
  File "/usr/local/lib/python3.10/site-packages/lightwave2/lightwave2.py", line 223, in async_get_hierarchy
    await self.async_update_featureset_states()
  File "/usr/local/lib/python3.10/site-packages/lightwave2/lightwave2.py", line 269, in async_update_featureset_states
    _LOGGER.warning("update_featureset_states: failed to read feature ({}), returned {}".format(x.features[y][0], value))
KeyError: <lightwave2.lightwave2.LWRFFeature object at 0x7f854d3340>
```

**Comment by mydliar** [comment]
Hi, started getting the same error message last few days (which roughly matches with my upgrade to Home Assistant 2022.7.0, but not exactly) after every scheduled HA restart. Typically an additional manual HA restart solves the issue, but it's a bit annoying. Thanks

**Comment by bigbadblunt** [comment]
I can't reproduce. Can you turn on additional logging in the integration options, and then post me a log if it recurs please?

**Comment by mSobhy90** [comment]
Sorry that was my bad 🙈 ... My hub was down, and that was causing the issue. Now it works like a charm.
